name: base
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - black
  - cudatoolkit=10.0
  - flake8-black
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pyglet
  - python=3.7
  - pytorch
  - torchvision
prefix: /opt/conda
